version: '3.8'

services:
  # Web Server Container (Nginx as reverse proxy + Node.js app)
  webserver:
    image: nginx:alpine
    container_name: ssd_webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - webapp
    restart: unless-stopped
    environment:
      - NGINX_USER=AUSTON IAN NG
      - NGINX_PASSWORD=2301768@sit.singaporetech.edu.sg

  # Node.js Web Application
  webapp:
    build: .
    container_name: ssd_webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - APP_USER=AUSTON IAN NG
      - APP_PASSWORD=2301768@sit.singaporetech.edu.sg
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./xato-net-10-million-passwords-1000.txt:/app/xato-net-10-million-passwords-1000.txt

  # Local Git Server
  gitserver:
    image: gitea/gitea:latest
    container_name: ssd_gitserver
    ports:
      - "3001:3000"
      - "2222:22"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://localhost:3001/
      - GITEA__admin__USERNAME=WHAT THE HELLY
      - GITEA__admin__EMAIL=2906969@sit.singaporetech.edu.sg
      - GITEA__admin__PASSWORD=2301768@sit.singaporetech.edu.sg
    restart: unless-stopped

volumes:
  gitea_data: